name: doggo
description: TCC

version: 1.0.0+1


environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite: ^1.0.5
  percent_indicator: ^2.1.1+1
  image_picker: ^0.6.4
  firebase_auth: ^0.14.0+5
  cloud_firestore:
  firebase_core: 0.4.0+8
  firebase_storage: 3.0.4
  provider: ^3.1.0


  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/img/dogg.png
    - assets/dog-breed-detector.tflite
    - assets/labels.txt


  uses-material-design: true

  fonts:
    - family: bosque
      fonts:
        - asset: font/BOSQUE.ttf
